# Generated by Django 5.0.7 on 2024-07-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configchoice',
            name='name',
        ),
    ]
